### ISSUE TITLE
Attestation.id is failing when trying to fully authenticate mock token - github examples

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/attestation#240] opened 2022-03-31 05:34 UTC
Steps:

get token from: https://tokenscript.github.io/token-negotiator-gh-pages/ticket-issuer-url-website/build/index.html

try to complete flow: https://tokenscript.github.io/token-negotiator-gh-pages/hotel-bogota-active-negotiation-website/build/index.html

bundle.js:124          POST https://backend-stage.attestation.id/api/attestation/magic-link net::ERR_ABORTED 400
createAndReturnAttestationFromMagicLink @ bundle.js:124
await in createAndReturnAttestationFromMagicLink (async)
(anonymous) @ bundle.js:124
(anonymous) @ bundle.js:124
i @ bundle.js:124
s @ bundle.js:124
(anonymous) @ bundle.js:124
bundle.js:124 0x647935C1bfA643D27AFe0F32A5357975b56B771d
bundle.js:124 0x647935C1bfA643D27AFe0F32A5357975b56B771d
bundle.js:124          POST https://backend-stage.attestation.id/api/attestation/magic-link net::ERR_ABORTED 400

**Comment by foxgem** [comment] 2022-03-31 07:32
I tried as the step described here. I got this error:

<img width="943" alt="image" src="https://user-images.githubusercontent.com/304052/161001686-02f1f3ab-4ff2-4db7-9bae-8e4854938da6.png">

it seems the magic link attestation is created but validation failed. I have no idea about magiclink and this error. @oleggrib can you help this?

**Comment by nicktaras** [comment] 2022-04-01 04:19
Thanks @foxgem.

@oleggrib - I hope your travel is going well. Would you have some time to take a look at this issue?

We are quite likely to be showing a live demo to a potential partner next Monday.

Could the mock attestations be outdated? 

Thanks guys.

**Comment by micwallace** [comment] 2022-04-01 05:03
Hey Nick, 

I suspect we will need to update authenticator.js on our side to support the new schema. The packaged version already has the ability to use the new schema. I'll test this out a little later.

On 1 April 2022 3:19:53 pm AEDT, Nick ***@***.***> wrote:
>Thanks @foxgem.
>
***@***.*** - I hope your travel is going well. Would you have some time to take a look at this issue?
>
>We are quite likely to be showing a live demo to a potential partner next Monday.
>
>Could the mock attestations be outdated? 
>
>Thanks guys. 
>
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/TokenScript/attestation/issues/240#issuecomment-1085404538
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nicktaras** [comment] 2022-04-01 05:12
Thanks so much @oleggrib let me know if I can help with the testing / code changes.

**Comment by jot2re** [comment] 2022-04-01 13:35
The issue is an inconsistency between versions. The request in question has the legacy description "Linking Ethereum address to phone or email" whereas it is supposed to now be "Creating email attestation".
The latest version of attestation.jar should be able to verify both cases.

However, what is very weird is that when I run this locally with the latest version of attestation.jar, it still fails, whereas if a I use the request to run a unit test on attestation.jar, things go well.

**Comment by nicktaras** [comment] 2022-04-02 10:44
<img width="802" alt="Screen Shot 2022-04-02 at 9 43 02 pm" src="https://user-images.githubusercontent.com/6808817/161379601-6ad1cf80-3825-4733-80c5-6ec9ae428271.png">

Just sharing a new error shown inside the console.

**Comment by nicktaras** [comment] 2022-04-02 10:51
Thanks @jot2re and @micwallace.

Do we have the new schema on github / notion / dev notes?

**Comment by nicktaras** [comment] 2022-04-02 11:55
In general for these types of changes, let's put some time in next meeting to make some actions to stabilise the workflow of changes, so if attestation.id changes the example will continue to function.

**Comment by nicktaras** [comment] 2022-04-03 23:50
Thanks so much @oleggrib for your help towards the fix for the changes to attestation.id

"Can you try to build and use authenticator from branch "js_pr212" ? should fix the issue with attestation. Tell me if it help." comment from Oleh copied from conversation. 

We'll try this and see if it resolves the issue.

**Comment by jot2re** [comment] 2022-04-04 07:43
> In general for these types of changes, let's put some time in next meeting to make some actions to stabilise the workflow of updates, so if attestation.id changes the examples will continue to function.

Yes, totally agree. I am sorry, it has been my fault of not getting things sufficiently integration tested before merging new changes.

**Comment by jot2re** [comment] 2022-04-04 07:44
Please be aware it seems there is still a bug with the JS/TS code in this branch, on which I am waiting on some feedback from @oleggrib. Which is why I have not merged it yet.

**Comment by nicktaras** [comment] 2022-04-06 00:10
> 

That's ok Tore. Thanks so much for your help guys.

**Comment by jot2re** [comment] 2022-04-06 14:09
I have made a new release of attestation.jar and authenticator.js, 0.3.17 and I have asked @foxgem to test and release it.
I did a manual test (of the issuance of an attestation based on email) which worked. Although I have not made a manual test of the magicLink flow.
@nicktaras if you will help me to make changes to the examples in the right places, to allow for a test of the flow using a locally hosted attestation.id instance, I would be happy, since it would allow me to better manually test changes before releases.

**Comment by micwallace** [comment] 2022-04-08 07:51
Hey all, the latest build of token negotiator now includes the attestation NPM package and is validating correctly with attestation.id. I have had to include old versions of SignedDevconTicket for compatibility, so that need to be looked at to get the updated versions working. Please see #239

**Closed** 2022-05-13 14:58 UTC
