### ISSUE TITLE
build failed with eip712 errors + using deprecated API in IdentifierAttestation.java

### ISSUE THREAD

**Issue by colourful-land** [TokenScript/attestation#147] opened 2021-06-30 07:09 UTC
````
$ java --version
openjdk 14.0.2 2020-07-14
$ gradle build

> Task :compileJava
Note: /home/vnaeli/IdeaProjects/attestation/src/main/java/com/alphawallet/attestation/IdentifierAttestation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test

TestAttestationUsageEip712 > otherTimeLimit() FAILED
    org.opentest4j.AssertionFailedError at TestAttestationUsageEip712.java:103

TestAttestationUsageEip712 > testDecoding() FAILED
    org.opentest4j.AssertionFailedError at TestAttestationUsageEip712.java:112

Eip712Test > referenceEncodingOtherOrder() FAILED
    org.opentest4j.AssertionFailedError at Eip712Test.java:58

Eip712Test > referenceEncoding() FAILED
    org.opentest4j.AssertionFailedError at Eip712Test.java:73

228 tests completed, 4 failed
````

**Comment by jot2re** [comment] 2021-07-01 13:25
This is a bit weird, I just ran the tests on main locally and I don't have any failures.

**Comment by colourful-land** [comment] 2021-07-05 00:32
I can't get openjdk 15 running on my host but I got both 14 and 16 running and both produce errors. The following is copied from a host running openkdj16, running test case `public void referenceEncoding()` from `./src/test/java/org/tokenscript/eip712/Eip712Test.java`

Notice how the value of `signatureInHex` differs from one to another.

@JamesSmartCell can you reproduce the issue?

````
Configuration on demand is an incubating feature.
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test
jul. 05, 2021 10:29:12 A. M. org.junit.platform.launcher.core.EngineDiscoveryOrchestrator lambda$logTestDescriptorExclusionReasons$7
INFORMACIÓN: 0 containers and 18 tests were Method or class mismatch

expected: <{"signatureInHex":"0x71d1b3925bcc1482e34f4ae6f5560e27e6a7f3ad48acefb8089f3d450b3b6e225f28d2a73f1b08956e5b75c5ff0552e251492b493849aac8f4a9cd8cc54bee231c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 01:00:00 GMT+0100\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}> but was: <{"signatureInHex":"0xbadb4457d349474db1e1b14414bcb0dbbba903d1d3ddd6c742aca9903a59b73567f314f41a13349d07f2519b07734406491a7f31810218a50757b1700f557bcd1c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 10:00:00 GMT+1000\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}>
Expected :{"signatureInHex":"0x71d1b3925bcc1482e34f4ae6f5560e27e6a7f3ad48acefb8089f3d450b3b6e225f28d2a73f1b08956e5b75c5ff0552e251492b493849aac8f4a9cd8cc54bee231c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 01:00:00 GMT+0100\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}
Actual   :{"signatureInHex":"0xbadb4457d349474db1e1b14414bcb0dbbba903d1d3ddd6c742aca9903a59b73567f314f41a13349d07f2519b07734406491a7f31810218a50757b1700f557bcd1c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 10:00:00 GMT+1000\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}
<Click to see difference>

org.opentest4j.AssertionFailedError: expected: <{"signatureInHex":"0x71d1b3925bcc1482e34f4ae6f5560e27e6a7f3ad48acefb8089f3d450b3b6e225f28d2a73f1b08956e5b75c5ff0552e251492b493849aac8f4a9cd8cc54bee231c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 01:00:00 GMT+0100\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}> but was: <{"signatureInHex":"0xbadb4457d349474db1e1b14414bcb0dbbba903d1d3ddd6c742aca9903a59b73567f314f41a13349d07f2519b07734406491a7f31810218a50757b1700f557bcd1c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 10:00:00 GMT+1000\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at org.tokenscript.eip712.Eip712Test.referenceEncoding(Eip712Test.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:832)
````

**Comment by jot2re** [comment] 2021-07-05 08:19
Okay, based on @colourful-land's observation, it seem that the issue is simply that the "randomness" used is not deterministic when Weiwu is running it. 
This can either be an issue with these two lines in  `SignatureUtility`:
``` HMacDSAKCalculator randomnessProvider = new HMacDSAKCalculator(new KeccakDigest(256));
        randomnessProvider.init(key.getParameters().getN(), key.getD(), digest);```
Or simply that the following does not produce a deterministic result (and thus different keys)
```rand = SecureRandom.getInstance("SHA1PRNG");
    rand.setSeed("seed".getBytes());```

**Comment by jot2re** [comment] 2021-07-05 08:42
Having looked further into this, it seems to be an issue with the default security provider being different on different systems. I have tried committed a change forcing it to use the Sun provider specification. Which, as far as I can read, _should_ also be available on openJdk systems (which is also what I run).

**Comment by colourful-land** [comment] 2021-07-05 09:12
didn't work. even with c443aa3359461126d4e9c18dc9356465afb485c6 I still got this:

````
> Task :test
jul. 05, 2021 7:10:12 P. M. org.junit.platform.launcher.core.EngineDiscoveryOrchestrator lambda$logTestDescriptorExclusionReasons$7
INFORMACIÓN: 0 containers and 18 tests were Method or class mismatch

expected: <{"signatureInHex":"0x71d1b3925bcc1482e34f4ae6f5560e27e6a7f3ad48acefb8089f3d450b3b6e225f28d2a73f1b08956e5b75c5ff0552e251492b493849aac8f4a9cd8cc54bee231c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 01:00:00 GMT+0100\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}> but was: <{"signatureInHex":"0xbadb4457d349474db1e1b14414bcb0dbbba903d1d3ddd6c742aca9903a59b73567f314f41a13349d07f2519b07734406491a7f31810218a50757b1700f557bcd1c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 10:00:00 GMT+1000\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}>
Expected :{"signatureInHex":"0x71d1b3925bcc1482e34f4ae6f5560e27e6a7f3ad48acefb8089f3d450b3b6e225f28d2a73f1b08956e5b75c5ff0552e251492b493849aac8f4a9cd8cc54bee231c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 01:00:00 GMT+0100\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}
Actual   :{"signatureInHex":"0xbadb4457d349474db1e1b14414bcb0dbbba903d1d3ddd6c742aca9903a59b73567f314f41a13349d07f2519b07734406491a7f31810218a50757b1700f557bcd1c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 10:00:00 GMT+1000\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}
````

**Comment by jot2re** [comment] 2021-07-05 15:36
@fyang1024 discovered the issue was in fact related to local time-zone being used when constructing attestations. This should be fixed now.

**Closed** 2021-07-11 12:05 UTC
